name:  ${project.artifactId}
version:  ${project.version}
description:  Rewards!
author:  se1by
website:  http://www.bitbyterstudios.com
softdepend: [Votifier]

main:  com.bitbyterstudios.rewardme.RewardMe

commands:
  reward:
    description:  Buy
    usage:  /<command>
  points:
    description:  points
    usage:  /<command>
  rewards:
    description: rewards
    usage:  /<command>
  generateredeem:
    description: generate redeemcode
    usage: /<command> <name> <expirationdate>
    aliases: genred
  useredeem:
    description: use redeemcode
    usage: /<command> <code>
    aliases: usered
  rewardme:
    description: help
    usage: /<command>
